---
title: "First Knit"
author: "Dominic Garibay"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct punctuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended a homeschooling program called The Blue Ridge Academy where I graduated in Summer 2023. For me Math comes more easier than English as I find working with numbers to be very straightforward and comes easy to me.
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
I have a Windows laptop where I am an 8 when it comes to computer stuff. I can navigate computer stuff I just need to be shown new things. My connection with the internet at home is ok with random internet shut outs but it's manageable and wont oppose an issue.  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
Dominic is fine as I dont like my nickname to be used. However if you do wanna use a nickname im fine with Dom or dominos just ask if you can call me that.   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
I wish to be a lawyer and I want to study law with political science.I am aiming for my BS or Bachlors in Science. In the end I want to go to law school as soon as possible and be able to earn money for my family.   
 



## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
I have not gone to a foreign country and if I were to go to one it would be South Korea.I have not been in the military and I would be in the Marines as I think it's the most useful combated branch.   
  



## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
I am taking Math 116 and I over qualify for Math 115 and my grade goal is for the highest one possible to have it stand out in transcripts.  
 






  

